blank_issues_enabled: false
contact_links:
  - name: Security Issues
    url: https://github.com/KAESTechnology/HANS/docs/SECURITY.md
    about: Please report security issues privately as described in docs/SECURITY.md
